### ISSUE TITLE
Esp32 s2 mini

### ISSUE THREAD

**Issue by Albafika83** [dchristl/esp32_nat_router_extended#100]
Hi,
doesn't work for the esp32 s2 mini ?
regards

**Comment by dchristl** [comment]
Hello,

is this a question or a bug report? Yes, the S2 mini works. You find an image for flashing at the release page.

Regards,
Danny

**Comment by Albafika83** [comment]
indeed, I downloaded the wrong image ! I m an idiot !
it works great !
great job !
thanks
