### ISSUE TITLE
Do I have to have the same bootloader and partition

### ISSUE THREAD

**Issue by nekef** [dchristl/esp32_nat_router_extended#107]
I am just wondering if I have to have the same partition and bootloader for esp32 c3 from the original code by Martin-ger because when I download zip file and upload the binary file the 0x10000, and nothing to 0x0 and 0x8000, it just does not work. Please answer.

Regards nekef

**Comment by dchristl** [comment]
Hello @nekef ,

the bootloader should be the same, but the partition has changed. Mainly because of the OTA-Parttion.

Regards,
Danny
