### ISSUE TITLE
Bandwidth Controller or  Load Balance

### ISSUE THREAD

**Issue by adi160885** [dchristl/esp32_nat_router_extended#108]
your application is very impressive, can you add a "Bandwidth Controller" to regulate *Mbps* or "Load balance", it might be very useful, thank you sir

**Comment by dchristl** [comment]
Hello @adi160885 ,

this is sadly not possible, because the framework (and maybe the hardware, too) of the ESP32 doesn't support this.

**Comment by adi160885** [comment]
What a shame, I use 4 ESP32 modules, all the average speed only reaches 3 -> 5 Mbps, is there something wrong with my ESP32 module, but if I use "gjroots ESP32-NAT Router +" the speed reaches 10 -> 14 Mbps. thank you in advance for answering my question 🙏

**Comment by dchristl** [comment]
The routing code of this project and gjroot's one are based on martin-gers work, so there should be no difference.

**Comment by adi160885** [comment]
Thank you for your answer, your project is very good
