### ISSUE TITLE
ESP32C3 Seeed XIAO  cant install or upgrade the fw v7.1.0 

### ISSUE THREAD

**Issue by kondakos** [dchristl/esp32_nat_router_extended#119]
I try to clean install ,  upgrade and   OTA  (from 6.5.0 and 7.0.0) a ESP32C3 Seeed XIAO   to  v7.1.0 but every time no working result.
The bellow log was from a OTA attempt. 

I (4665) esp_netif_handlers: sta ip: 192.168.1.119, mask: 255.255.255.0, gw: 192.168.1.1
I (4665) ESP32NRE: Got IP: http://192.168.1.119
I (4675) DNSServer: DNS Server stopped
I (4675) ESP32NRE: Setting DNS server to upstream DNS
I (4675) ESP32NRE: set dns to: 192.168.1.1
I (20495) wifi:new:<11,2>, old:<11,0>, ap:<11,2>, sta:<11,0>, prof:1
I (20505) wifi:station: a0:a8:cd:72:c2:a7 join, AID=1, bgn, 40D
I (20515) ESP32NRE: Station connected
I (20615) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.4.2
I (21235) wifi:<ba-add>idx:2 (ifx:1, a0:a8:cd:72:c2:a7), tid:0, ssn:64, winSize:64
I (27635) IndexHandler: Allocating additional 11499 bytes for config page.
I (41505) cmd_router: hostname esp32nre9117
I (41505) Advancedhandler: Current DNS is: 192.168.1.1
I (41505) Advancedhandler: Current DNS is: 192.168.1.1
I (41505) Advancedhandler: Allocating additional 10332 bytes for advanced page.
I (54395) OTA: Requesting OTA page with additional size of 1582
I (57665) OTA: Getting with post: func=versioncheck
I (58535) OTA: Download finished
I (58545) OTA: Version and changelog download succesful. File size is: 113 Bytes
I (58565) OTA: Requesting OTA page with additional size of 1664
W (419595) esp_https_ota: Continuing with insecure option because CONFIG_ESP_HTTPS_OTA_ALLOW_HTTP is set.
I (419825) OTA: Requesting OTA-Log page
I (420415) OTA: Download size is 1419 kB
I (420415) esp_https_ota: Starting OTA...
I (420415) esp_https_ota: Writing to partition subtype 17 at offset 0x190000
I (420535) OTA: 0 of 1419 kB
I (421585) OTA: Requesting OTA-Log page
I (422765) OTA: Requesting OTA-Log page
I (423915) OTA: Requesting OTA-Log page
I (425025) OTA: Requesting OTA-Log page
I (425145) OTA: 142 of 1419 kB
I (426445) OTA: Requesting OTA-Log page
I (427625) OTA: Requesting OTA-Log page
I (428825) OTA: Requesting OTA-Log page
I (429765) OTA: 284 of 1419 kB
I (430025) OTA: Requesting OTA-Log page
I (431145) OTA: Requesting OTA-Log page
I (432355) OTA: Requesting OTA-Log page
I (433705) OTA: Requesting OTA-Log page
I (434175) OTA: 425 of 1419 kB
I (435065) OTA: Requesting OTA-Log page
I (436455) OTA: Requesting OTA-Log page
I (437895) OTA: Requesting OTA-Log page
I (438775) OTA: 568 of 1419 kB
I (439315) OTA: Requesting OTA-Log page
I (440675) OTA: Requesting OTA-Log page
I (442065) OTA: Requesting OTA-Log page
I (443425) OTA: 710 of 1419 kB
I (443525) OTA: Requesting OTA-Log page
I (444945) OTA: Requesting OTA-Log page
I (446375) OTA: Requesting OTA-Log page
I (447775) OTA: Requesting OTA-Log page
I (447995) OTA: 851 of 1419 kB
I (449115) OTA: Requesting OTA-Log page
I (450505) OTA: Requesting OTA-Log page
I (451685) OTA: Requesting OTA-Log page
I (452705) OTA: 994 of 1419 kB
I (453045) OTA: Requesting OTA-Log page
I (454455) OTA: Requesting OTA-Log page
I (455895) OTA: Requesting OTA-Log page
I (457295) OTA: Requesting OTA-Log page
I (457375) OTA: 1136 of 1419 kB
I (458655) OTA: Requesting OTA-Log page
I (460085) OTA: Requesting OTA-Log page
I (461485) OTA: Requesting OTA-Log page
I (461845) OTA: 1277 of 1419 kB
I (462915) OTA: Requesting OTA-Log page
I (464305) OTA: Requesting OTA-Log page
I (465675) OTA: Requesting OTA-Log page
I (466365) OTA: 1419 of 1419 kB
I (466365) esp_image: segment 0: paddr=00190020 vaddr=3c0e0020 size=68c08h (429064) map
I (466425) esp_image: segment 1: paddr=001f8c30 vaddr=3fc93c00 size=02f48h ( 12104)
I (466425) esp_image: segment 2: paddr=001fbb80 vaddr=40380000 size=04498h ( 17560)
I (466445) esp_image: segment 3: paddr=00200020 vaddr=42000020 size=db410h (898064) map
I (466565) esp_image: segment 4: paddr=002db438 vaddr=40384498 size=0f574h ( 62836)
I (466575) esp_image: segment 5: paddr=002ea9b4 vaddr=50000000 size=00020h (    32)
I (466585) esp_image: segment 0: paddr=00190020 vaddr=3c0e0020 size=68c08h (429064) map
I (466655) esp_image: segment 1: paddr=001f8c30 vaddr=3fc93c00 size=02f48h ( 12104)
I (466655) esp_image: segment 2: paddr=001fbb80 vaddr=40380000 size=04498h ( 17560)
I (466665) esp_image: segment 3: paddr=00200020 vaddr=42000020 size=db410h (898064) map
I (466805) esp_image: segment 4: paddr=002db438 vaddr=40384498 size=0f574h ( 62836)
I (466815) esp_image: segment 5: paddr=002ea9b4 vaddr=50000000 size=00020h (    32)
I (466865) OTA: OTA update succesful. The device is restarting.
I (467035) OTA: Requesting OTA-Log page
I (470035) Timer: Restarting now...
I (470035) wifi:state: run -> init (0)
I (470035) wifi:pm stop, total sleep time: 87253922 us / 466891269 us

I (470045) wifi:<ba-del>idx:0, tid:0
I (470045) wifi:new:<11,2>, old:<11,2>, ap:<11,2>, sta:<11,0>, prof:1
I (470045) wifi:station: a0:a8:cd:72:c2:a7 leave, AID = 1, bss_flags is 134243, bss:0x3fcaf5ec
I (470055) wifi:new:<11,0>, old:<11,2>, ap:<11,2>, sta:<11,0>, prof:1
I (470055) wifi:<ba-del>idx:2, tid:0
I (470045) ESP32NRE: disconnected - retry to connect to the STA
I (470075) ESP32NRE: retry to connect to the STA
I (470085) ESP32NRE: Station disconnected
I (470155) wifi:flush txq
I (470155) wifi:stop sw txq
I (470155) wifi:lmac stop hw txq
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40048b82
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x1704
load:0x403cc710,len:0x968
load:0x403ce710,len:0x2f9c
entry 0x403cc710
I (15) boot: ESP-IDF 5.1.2 2nd stage bootloader
I (15) boot: compile time Mar  3 2024 16:06:33
I (15) boot: chip revision: v0.4
I (18) boot.esp32c3: SPI Speed      : 80MHz
I (23) boot.esp32c3: SPI Mode       : DIO
I (28) boot.esp32c3: SPI Flash Size : 4MB
I (32) boot: Enabling RNG early entropy source...
I (38) boot: Partition Table:
I (41) boot: ## Label            Usage          Type ST Offset   Length
I (49) boot:  0 nvs              WiFi data        01 02 00009000 00005000
I (56) boot:  1 otadata          OTA data         01 00 0000e000 00002000
I (64) boot:  2 ota_0            OTA app          00 10 00010000 00177000
I (71) boot:  3 ota_1            OTA app          00 11 00190000 00177000
I (78) boot: End of partition table
I (83) esp_image: segment 0: paddr=00190020 vaddr=3c0e0020 size=68c08h (429064) map
I (161) esp_image: segment 1: paddr=001f8c30 vaddr=3fc93c00 size=02f48h ( 12104) load
I (163) esp_image: segment 2: paddr=001fbb80 vaddr=40380000 size=04498h ( 17560) load
I (170) esp_image: segment 3: paddr=00200020 vaddr=42000020 size=db410h (898064) map
I (321) esp_image: segment 4: paddr=002db438 vaddr=40384498 size=0f574h ( 62836) load
I (333) esp_image: segment 5: paddr=002ea9b4 vaddr=50000000 size=00020h (    32) load
I (340) boot: Loaded app from partition at offset 0x190000
I (340) boot: Disabling RNG early entropy source...
I (353) cpu_start: Unicore app
I (362) cpu_start: Pro cpu start user code
I (362) cpu_start: cpu freq: 160000000 Hz
I (362) cpu_start: Application information:
I (365) cpu_start: Project name:     esp32_nat_router_extended
I (372) cpu_start: App version:      7.1.0
I (376) cpu_start: Compile time:     Apr 21 2024 12:57:19
I (383) cpu_start: ELF file SHA256:  f304dfb555728d97...
I (389) cpu_start: ESP-IDF:          5.2.1
I (393) cpu_start: Min chip rev:     v0.3
I (398) cpu_start: Max chip rev:     v1.99
I (403) cpu_start: Chip rev:         v0.4
I (408) heap_init: Initializing. RAM available for dynamic allocation:
I (415) heap_init: At 3FC9BAC0 len 00024540 (145 KiB): RAM
I (421) heap_init: At 3FCC0000 len 0001C710 (113 KiB): Retention RAM
I (428) heap_init: At 3FCDC710 len 00002950 (10 KiB): Retention RAM
I (435) heap_init: At 50000020 len 00001FC8 (7 KiB): RTCRAM
I (442) spi_flash: detected chip: generic
I (446) spi_flash: flash io: dio
I (450) sleep: Configure to isolate all GPIO pins in sleep state
I (457) sleep: Enable automatic switching of GPIO sleep configuration
I (464) main_task: Started on CPU0
I (464) main_task: Calling app_main()

**Comment by dchristl** [comment]
Hello, 

the log seems all Ok. The update was successfully. It logs the new App version 7.1.0 as well after the reboot. There is also no error in the log. I don't really see what is wrong.

**Comment by kondakos** [comment]
The same happened when i try to update with fw 7.1.1. The log of  update stoped and ESP32C3 hanged without AP or communication with serial port.

**Comment by dchristl** [comment]
This seems to be a hardware/driver problem. The firmware actually has no influence on the connectivity to the operating system. Does everything work if you ignore the OTA update and flash "normally"? Have you tried to update without a PC-connected cable? Does the device comes up afterwards?

**Comment by kondakos** [comment]
The fw7.1.1 installed successfully via OTA update.
