### ISSUE TITLE
iptables or proxy support

### ISSUE THREAD

**Issue by them1k** [dchristl/esp32_nat_router_extended#125]
**### My usecase**

Is possible to use this repeater to connect to my mobile phone WIFI and have all the http and https traffic go through a public proxy? Could some kind of configuration or support for iptables be added? or would the ESP32 not be able to handle it due to the amount of traffic it would generate?

Thank you, and I hope my question is not a bother.

**Comment by StruckGuide8154** [comment]
i want this too!

**Comment by dchristl** [comment]
Most "real" routers have a Linux system (iptables needs the kernel) as firmware and even expensive devices rarely have such a filter. Even if I were to consider it even remotely realistic to implement something like this with reasonable effort, the resources of the ESP32 will not be nearly sufficient. So, sorry, unfortunately that's not realistic
