### ISSUE TITLE
Advanced clients settings

### ISSUE THREAD

**Issue by StruckGuide8154** [dchristl/esp32_nat_router_extended#126]
Hey, is it possible to make it so i can block a client from using the internet/from joining the network by blocking there MAC adress, aswell as this is a whitelist/blackist/none toggle also possible as i think it would be cool to be able to have a public network for me and my friends only to where i can say only some MAC adresses are allowed to use it goin therough the connected stations or some are not.

Second to last, is adding a bandwith moniter/limiter possible, to where by each station you can set a kbps limit to them, a max they can use and a max overall like 12mb bandwidth, finally a moniter for how much that mac has used in the past aswell as an overall limiter for bandwidth per second, overall and a graph moniter. On this note a groups section to allow me to add users to a group and base bandwidth off of that and show stats on groups. 

Finally, a tricky one, is it possible to add a guest network or second one by toggle besite the current one, same relay but maybe for a guest net with limited bandwidth?

Thanks!

**Comment by dchristl** [comment]
Sorry, but you want functions that "real" routers costing well over 200 euros don't have on a 3 euro chip? Neither the hardware of the chip (guest network) nor the performance and memory space (monitoring, filter) can provide this. In its current mode, the ESP32 is already much slower than a real router. Therefore, your wishes cannot be realised. Maybe you should buy an expensive router and/or have a look at OpenWRT or similar. There may be firmwares that support something like this.
