### ISSUE TITLE
New feature: Reset pin

### ISSUE THREAD

**Issue by ErfanDL** [dchristl/esp32_nat_router_extended#23]
Hi. I love this project very much. is it possible to add an option for factory reset device by hardware pin ?

thanks.

**Comment by dchristl** [comment]
Hello ErfanDL,

you can [try the new 2.0.0 beta release](https://github.com/dchristl/esp32_nat_router_extended/releases/tag/v2.0.0_beta) and read the [documentation](https://github.com/dchristl/esp32_nat_router_extended/blob/dev/docs/advanced.md#resetting-the-device-erasing-the-flash) how to use this feature. Any feedback and test will be appreciated. Thanks.

**Comment by ErfanDL** [comment]
> Hello ErfanDL,
> 
> you can [try the new 2.0.0 beta release](https://github.com/dchristl/esp32_nat_router_extended/releases/tag/v2.0.0_beta) and read the [documentation](https://github.com/dchristl/esp32_nat_router_extended/blob/dev/docs/advanced.md#resetting-the-device-erasing-the-flash) how to use this feature. Any feedback and test will be appreciated. Thanks.

Hi.
Nice work. Thank you for your attention.
