### ISSUE TITLE
v2.2.0 constant reboot

### ISSUE THREAD

**Issue by blueskiesok** [dchristl/esp32_nat_router_extended#32]
on older version 1.0.2beta works.
when trying v2.2.0 constant reboot similar to previous reboot issue reported.

**Comment by dchristl** [comment]
The partition table has changed at the [v2.1.0 ](https://github.com/dchristl/esp32_nat_router_extended/releases/tag/v2.1.0). An update is not possible, you have to execute a full reset like described [here](https://github.com/dchristl/esp32_nat_router_extended#first-install-reset)

**Comment by blueskiesok** [comment]
This was on a fresh full install?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by dchristl** [comment]
Have you erased the flash before? If not, please try. Otherwise I need more details about your device and some kind of log (reboot and debug flash log). I only have 3 different devices for testing, so maybe this is an other one with other specifications.

**Comment by blueskiesok** [comment]
Just to check, I tried using Linux instead of windows.  Everything flashed and worked.  So apparently my problem has something to do with Windows 10.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dchristl** [comment]
Great to hear that, maybe your esp-idf on Windows is too old. Some older versions had some problems with custom partition tables.
