### ISSUE TITLE
Scan Handler writes permanently

### ISSUE THREAD

**Issue by Clox1800** [dchristl/esp32_nat_router_extended#33]
Hi,
First, thanks for this great job, initialised by martin ger.
When using CLI via a serial connection, output is occupied by messages from Wifi Handler.
Is it possible to deactivate these messages ?

**Comment by dchristl** [comment]
Hi,

sorry this is not possible, but you can filter the ouput. Every class/file is implemented with a different log-Tag, so you can grep (in Linux) by this. You can also check [ESP32 IDF-Monitor](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-monitor.html), that has also an option for [filtering](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-monitor.html#output-filtering)
