### ISSUE TITLE
Telnet does not work

### ISSUE THREAD

**Issue by Clox1800** [dchristl/esp32_nat_router_extended#34]
Hi,
I want to use CLI to configure my ESP32 Nat Router.
Using Putty, I can open a session in serial mode (Args: Num of port COM, and baud rate).
Of course, i need to use a serial link via USB cable.

But, if I try with a Telnet session (Args: 192.168.4.1, port 7777, and I am also connected with the AP network ), it's not possible.
I get this error: Network error: Connexion refused.

Thanks for informations.

**Comment by dchristl** [comment]
Hi,

this doesn't work like you expect. There is no Telnet server implemented, just a web server and nothing else. The output writes only to serial connection.
