### ISSUE TITLE
Allways reboot

### ISSUE THREAD

**Issue by pipi61** [dchristl/esp32_nat_router_extended#4]
Hi!
I erase flash, then flash your binary files. The esp32 reboot allways:
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:5820
ho 0 tail 12 room 4
load:0x40078000,len:13800
ho 0 tail 12 room 4
load:0x40080400,len:3412
entry 0x40080634
[0;32mI (372) cpu_start: Pro cpu up.[0m
[0;32mI (373) cpu_start: Starting app cpu, entry point is 0x40081f44[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (387) cpu_start: Pro cpu start user code[0m
[0;32mI (387) cpu_start: cpu freq: 160000000[0m
[0;32mI (387) cpu_start: Application information:[0m
[0;32mI (391) cpu_start: Project name:     esp32_nat_router[0m
[0;32mI (397) cpu_start: App version:      1edc145[0m
[0;32mI (402) cpu_start: Compile time:     Oct 30 2021 12:58:15[0m
[0;32mI (408) cpu_start: ELF file SHA256:  a4e1a55070fd8950...[0m
[0;32mI (414) cpu_start: ESP-IDF:          4.3.0[0m
[0;32mI (419) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (426) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (432) heap_init: At 3FFB8478 len 00027B88 (158 KiB): DRAM[0m
[0;32mI (438) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM[0m
[0;32mI (445) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (451) heap_init: At 400975B8 len 00008A48 (34 KiB): IRAM[0m
[0;32mI (458) spi_flash: detected chip: gd[0m
[0;32mI (462) spi_flash: flash io: dio[0m
[0;32mI (467) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (534) ESP32 NAT router: Command history disabled[0m
I (544) wifi:wifi driver task: 3ffc2070, prio:23, stack:3584, core=0
[0;32mI (544) system_api: Base MAC address is not set[0m
[0;32mI (544) system_api: read default base MAC address from EFUSE[0m
I (554) wifi:wifi firmware version: c7d0450
I (554) wifi:wifi certification version: v7.0
I (554) wifi:config NVS flash: enabled
I (554) wifi:config nano formating: disabled
I (564) wifi:Init data frame dynamic rx buffer num: 32
I (564) wifi:Init management frame dynamic rx buffer num: 32
I (574) wifi:Init management short buffer num: 32
I (574) wifi:Init dynamic tx buffer num: 32
I (584) wifi:Init static rx buffer size: 1600
I (584) wifi:Init static rx buffer num: 10
I (584) wifi:Init dynamic rx buffer num: 32
[0;32mI (594) wifi_init: rx ba win: 6[0m
[0;32mI (594) wifi_init: tcpip mbox: 32[0m
[0;32mI (604) wifi_init: udp mbox: 6[0m
[0;32mI (604) wifi_init: tcp mbox: 6[0m
[0;32mI (604) wifi_init: tcp tx win: 5744[0m
[0;32mI (614) wifi_init: tcp rx win: 5744[0m
[0;32mI (614) wifi_init: tcp mss: 1440[0m
[0;32mI (624) wifi_init: WiFi IRAM OP enabled[0m
[0;32mI (624) wifi_init: WiFi RX IRAM OP enabled[0m
[0;32mI (2634) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07[0m
I (2724) wifi:mode : softAP (30:ae:a4:1b:72:95)
I (2724) wifi:Total power save buffer number: 16
I (2724) wifi:Init max length of beacon: 752/752
I (2724) wifi:Init max length of beacon: 752/752
[0;32mI (2734) ESP32 NAT router: wifi_init_ap with default finished.[0m
[0;32mI (2734) gpio: GPIO[2]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 [0m
[0;32mI (2734) ESP32 NAT router: NAT is enabled[0m
[0;32mI (2754) ESP32 NAT router: Starting config web server[0m
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x400d4166  PS      : 0x00060330  A0      : 0x800d36f6  A1      : 0x3ffbbeb0  
A2      : 0x00000000  A3      : 0x3f400200  A4      : 0x3f4006a0  A5      : 0x00000ac2  
A6      : 0x3f400200  A7      : 0x40404040  A8      : 0x800d4163  A9      : 0x3ffbbe70  
A10     : 0x00001102  A11     : 0x3ffbbef0  A12     : 0x3f400664  A13     : 0x3ffbbef0  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000017  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4000164d  LEND    : 0x40001667  LCOUNT  : 0xfffffffd  

Backtrace:0x400d4163:0x3ffbbeb0 0x400d36f3:0x3ffbbf20 0x40156c8d:0x3ffbbf60 0x4008db51:0x3ffbbf80

ELF file SHA256: a4e1a55070fd8950

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:5820
ho 0 tail 12 room 4
load:0x40078000,len:13800
ho 0 tail 12 room 4
load:0x40080400,len:3412
entry 0x40080634
[0;32mI (372) cpu_start: Pro cpu up.[0m
[0;32mI (372) cpu_start: Starting app cpu, entry point is 0x40081f44[0m
.............................
comment: the martin-ger version work.
Thank You

**Comment by dchristl** [comment]
Hi pipi61,

it seems to be connected to issue  #3. I already resolved this, so please can you try the latest beta available [here](https://github.com/dchristl/esp32_nat_router_extended/releases/tag/v1.0.2.beta)

If this resolve your issue, please give feedback.

Thank you

**Comment by dchristl** [comment]
This is resolved with [1.1.0-release](/dchristl/esp32_nat_router_extended/releases/tag/v1.1.0)

**Comment by pipi61** [comment]
Thank You for fast reply. The Beta version good work. I measure 10Mbps transfer speed, this good.
Good work.
![Névtelen](https://user-images.githubusercontent.com/9288482/150678942-05fe30fe-4355-4b25-9d5d-33fee126ddd0.png)
one note: wifi scanning only works for the first time. After the ssid and pass settings, the wifi scan did not find any station, but the router is still working

**Comment by pipi61** [comment]
Hi!
in  v1.1.1 the scan working.
Thank You
comment: I found a lost letter "v" :))
![Névtelen](https://user-images.githubusercontent.com/9288482/151445770-16fdfb37-9b3c-4568-b982-b0393410edc7.png)

**Comment by pipi61** [comment]
idea: I use it in another project, wifi.scannetwork runs immediately after poweron (before starting the router parameters) and stores the wifi host parameters in variables. If it is in the request station list of the web page, no restart and reconnection is required, only a list from variables

**Comment by dchristl** [comment]
Thanks for your feedback,

> comment: I found a lost letter "v" :))

This should be solved with the latest [Beta](https://github.com/dchristl/esp32_nat_router_extended/releases/tag/v1.2.0-beta)

> idea: I use it in another project, wifi.scannetwork runs immediately after poweron (before starting the router parameters) and stores the wifi host parameters in variables. If it is in the request station list of the web page, no restart and reconnection is required, only a list from variables

Sorry, but I didn't really understand your mentioned workflow. Do you scan every time you reboot the controller? This takes up to 20s and this is too long for a function you use not so much. Otherwise you have to set a flag (user wishes a scan) and also have to trigger a reboot/ reconnect. 
In my case the reboot can be replaced with a reset of the connection and a reconnect. But this is cumbersome and takes as much time as a reboot. My workflow is like:

1. disconnect from AP wifi
2. disconnect all clients
3. scan and save the result in nvs
4. Reboot
5. Show scan result on next client request 
6. Delete variable 


Regards
