### ISSUE TITLE
set_sta_static and portmap are not respected

### ISSUE THREAD

**Issue by zhgzhg** [dchristl/esp32_nat_router_extended#42]
Hello,
Currently it seems that setting a static IP address via (**set_sta_static**) doesn't do anything. The settings are preserved, but it seems they are not respected. Similarly the same happens with the **portmap** command.

**Comment by dchristl** [comment]
Hello zhgzhg,

yes this is possible, this is just a relict of the old base code and I don't use the configuration this way. I will have a look at it, when I have time.

Regards,
Danny
