### ISSUE TITLE
New Feature and suggestions.

### ISSUE THREAD

**Issue by Jackboy001** [dchristl/esp32_nat_router_extended#45]
Hope we can see the clients' information by clicking "* client(s) connected" button, like MAC address, IP address etc.
And seems likethe wifi scanning don't include hidden Wi-Fi, hope the hidden wifi can be displayed as *hidden wifi* or sth else.
User can select that *hidden wifi* and input the ssid and pwd to connect.
BTW thanks for this brilliant project, many useful features and the performance is very good!❤️

**Comment by dchristl** [comment]
Hello jackboy001,

thanks for your kind feedback. I already thought about additional client informations and I want to add it as soon as I have time. 
I don't really understand your suggestion with the hidden Wifi. That is the whole point of the hidden SSID, that you can't scan it. ;) I'm aware this is no security improvement and the scan can be still achieved with some tricks, if any client is connected.  You can always input the SSID and the password in the STA-settings and it should work. You don't need a scan before, if you know that there is any WiFi, neither hidden or not. 

Kind Regards
Danny
