### ISSUE TITLE
Compiling under esp-idf native toolchain

### ISSUE THREAD

**Issue by pcouderc12** [dchristl/esp32_nat_router_extended#68]
I use    esp-idf native toolchain and tried to compile under it.

I had some problems and I give workaround for them.

1-  At 1rst compile, I got:
#error "IP_NAPT must be defined"

The workaroud was to apply to the config the instructions given by https://github.com/martin-ger/esp32_nat_router, with idf.py menuconfig:

*Component config -> LWIP > [x] Enable copy between Layer2 and Layer3 packets.
*Component config -> LWIP > [x] Enable IP forwarding.
*Component config -> LWIP > [x] Enable NAT (new/experimental).

2- Then the main source directory for the project is to be set to "src" insread of "main" 
So changes are made to:

CMakeLists.txt : insert line after line 1:
list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_CURRENT_LIST_DIR}/src)

and to src/CMakeLists.txt: modify line 3:
idf_component_register(SRCS ${app_sources} INCLUDE_DIRS "." REQUIRES    esp_http_server  esp_timer  cmd_router cmd_system cmd_nvs wpa_supplicant fatfs esp_netif esp_http_client)

Then it compiles correctly

3- But partition table is not correct, I addd a custom partition.csv (using idf.py menuconfig):

`#` Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x6000,
phy_init, data, phy,     0xf000,  0x1000,
factory,  app,  factory, 0x10000, 1600K,

Then it seems to work fine.

I suppose it would be very simple to test environment in CMake and make CMakeLists.txt files compatiblewith various environments. But I am not competent enough to do it myself...
 

                                                                                            |

**Comment by dchristl** [comment]
see my post at #69
