### ISSUE TITLE
Errors :  ESP32 NAT router: disconnected - retry to connect to the AP

### ISSUE THREAD

**Issue by pcouderc12** [dchristl/esp32_nat_router_extended#69]
Using the toolchain described in #68, I get frequent disconnections, see full listing below.
I suspect a parameter is missing in configuration, and that  :
*Component config -> LWIP > [x] Enable copy between Layer2 and Layer3 packets.
*Component config -> LWIP > [x] Enable IP forwarding.
*Component config -> LWIP > [x] Enable NAT (new/experimental).

are not enough.

Full log for a connect from an android device: 

I (33) boot: ESP-IDF v5.2-dev-703-gefe919275e 2nd stage bootloader
I (33) boot: compile time Jun 24 2023 10:04:24
I (35) boot: Multicore bootloader
I (39) boot: chip revision: v3.0
I (43) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (52) boot.esp32: SPI Flash Size : 2MB
I (56) boot: Enabling RNG early entropy source...
I (62) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (73) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (80) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (88) boot:  2 factory          factory app      00 00 00010000 00190000
I (95) boot: End of partition table
I (99) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=6bdb8h (441784) map
I (267) esp_image: segment 1: paddr=0007bde0 vaddr=3ff80063 size=00008h (     8) load
I (267) esp_image: segment 2: paddr=0007bdf0 vaddr=3ffb0000 size=03980h ( 14720) load
I (279) esp_image: segment 3: paddr=0007f778 vaddr=40080000 size=008a0h (  2208) load
I (282) esp_image: segment 4: paddr=00080020 vaddr=400d0020 size=b8c34h (756788) map
I (563) esp_image: segment 5: paddr=00138c5c vaddr=400808a0 size=168c8h ( 92360) load
I (602) esp_image: segment 6: paddr=0014f52c vaddr=400c0000 size=00064h (   100) load
I (614) boot: Loaded app from partition at offset 0x10000
I (614) boot: Disabling RNG early entropy source...
I (625) cpu_start: Multicore app
I (626) cpu_start: Pro cpu up.
I (626) cpu_start: Starting app cpu, entry point is 0x400813fc
0x400813fc: call_start_cpu1 at /opt/esp-idf/components/esp_system/port/cpu_start.c:154

I (0) cpu_start: App cpu up.
I (643) cpu_start: Pro cpu start user code
I (643) cpu_start: cpu freq: 160000000 Hz
I (644) cpu_start: Application information:
I (648) cpu_start: Project name:     esp32_nat_router
I (654) cpu_start: App version:      v5.1.0-dirty
I (659) cpu_start: Compile time:     Jun 24 2023 10:02:08
I (665) cpu_start: ELF file SHA256:  aac433574...
I (671) cpu_start: ESP-IDF:          v5.2-dev-703-gefe919275e
I (677) cpu_start: Min chip rev:     v0.0
I (682) cpu_start: Max chip rev:     v3.99
I (687) cpu_start: Chip rev:         v3.0
I (692) heap_init: Initializing. RAM available for dynamic allocation:
I (699) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (705) heap_init: At 3FFB83C0 len 00027C40 (159 KiB): DRAM
I (711) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (717) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (724) heap_init: At 40097168 len 00008E98 (35 KiB): IRAM
I (732) spi_flash: detected chip: generic
I (735) spi_flash: flash io: dio
W (739) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (753) app_start: Starting scheduler on CPU0
I (757) app_start: Starting scheduler on CPU1
I (757) main_task: Started on CPU0
I (767) main_task: Calling app_main()
I (817) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (817) ESP32 NAT router: Device will boot up normally.
I (837) ESP32 NAT router: Command history disabled
I (847) cmd_router: ssid TP-LINK_2072
I (847) cmd_router: passwd
I (857) ESP32 NAT router: Netmask is set to 255.255.255.0, therefore private IP is 192.168.4.1
I (877) wifi:wifi driver task: 3ffc23c8, prio:23, stack:6656, core=0
I (907) wifi:wifi firmware version: 10c8635
I (907) wifi:wifi certification version: v7.0
I (907) wifi:config NVS flash: enabled
I (907) wifi:config nano formating: disabled
I (917) wifi:Init data frame dynamic rx buffer num: 32
I (917) wifi:Init management frame dynamic rx buffer num: 32
I (917) wifi:Init management short buffer num: 32
I (927) wifi:Init dynamic tx buffer num: 32
I (937) wifi:Init static rx buffer size: 1600
I (937) wifi:Init static rx buffer num: 10
I (947) wifi:Init dynamic rx buffer num: 32
I (947) wifi_init: rx ba win: 6
I (947) wifi_init: tcpip mbox: 32
I (947) wifi_init: udp mbox: 6
I (957) wifi_init: tcp mbox: 6
I (957) wifi_init: tcp tx win: 5744
I (957) wifi_init: tcp rx win: 5744
I (967) wifi_init: tcp mss: 1440
I (977) wifi_init: WiFi IRAM OP enabled
I (977) wifi_init: WiFi RX IRAM OP enabled
I (987) ESP32 NAT router: set dns to: 192.168.4.1
I (2987) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (3087) wifi:mode : sta (cc:db:a7:1e:3f:28) + softAP (cc:db:a7:1e:3f:29)
I (3087) wifi:enable tsf
I (3097) wifi:Total power save buffer number: 16
I (3097) wifi:Init max length of beacon: 752/752
I (3107) wifi:Init max length of beacon: 752/752
I (3107) ESP32 NAT router: wifi_init_apsta finished.
I (3117) esp_netif_lwip: DHCP server started on interface WIFI_AP_DEF with IP: 192.168.4.1
I (3117) ESP32 NAT router: connect to ap SSID: TP-LINK_2072 Password:
I (3127) DNSServer: Socket created
I (3127) DNSServer: Socket bound, port 53
I (3137) DNSServer: Waiting for data
I (3127) DNSServer: DNS Server started
I (3147) ESP32 NAT router: On board LED is enabled
I (3157) gpio: GPIO[2]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (3157) ESP32 NAT router: NAT is enabled
I (3157) ESP32 NAT router: Starting config web server
I (3167) HTTPServer: Keep alive is disabled
I (3177) HTTPServer: Starting server on port: '80'
I (3187) HTTPServer: Registering URI handlers

ESP32 NAT ROUTER
Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.
esp32> I (5947) ESP32 NAT router: disconnected - retry to connect to the AP
I (5947) ESP32 NAT router: retry to connect to the AP
I (8787) ESP32 NAT router: disconnected - retry to connect to the AP
I (8787) ESP32 NAT router: retry to connect to the AP
I (8837) wifi:new:<1,1>, old:<1,1>, ap:<1,1>, sta:<0,0>, prof:1
I (8837) wifi:station: 0c:c6:fd:34:e3:66 join, AID=1, bgn, 40U
I (8847) ESP32 NAT router: Station connected
I (9067) wifi:<ba-add>idx:2 (ifx:1, 0c:c6:fd:34:e3:66), tid:0, ssn:0, winSize:64
I (9067) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.4.2
I (9227) wifi:<ba-del>idx:2, tid:0
I (9227) wifi:<ba-add>idx:2 (ifx:1, 0c:c6:fd:34:e3:66), tid:0, ssn:4, winSize:64
I (9227) DNSServer: Received 47 bytes from 192.168.4.2 | DNS reply with len: 63
I (9247) DNSServer: Waiting for data
I (9247) DNSServer: Received 32 bytes from 192.168.4.2 | DNS reply with len: 48
I (9257) DNSServer: Waiting for data
I (9377) DNSServer: Received 34 bytes from 192.168.4.2 | DNS reply with len: 50
I (9377) DNSServer: Waiting for data
W (9387) wifi:Haven't to connect to a suitable AP now!
I (9387) IndexHandler: Allocating additional 10190 bytes for config page.
W (9527) httpd_txrx: httpd_sock_err: error in send : 104
W (9537) httpd_uri: httpd_uri: uri handler execution failed
W (9537) httpd_uri: httpd_uri: URI '/generate_204' not found
I (10437) DNSServer: Received 45 bytes from 192.168.4.2 | DNS reply with len: 61
I (10437) DNSServer: Waiting for data
I (10447) DNSServer: Received 38 bytes from 192.168.4.2 | DNS reply with len: 54
I (10457) DNSServer: Waiting for data
W (10837) httpd_parse: parse_block: request URI/header too long
W (10837) httpd_txrx: httpd_resp_send_err: 431 Request Header Fields Too Large - Header fields are too long
I (11637) ESP32 NAT router: disconnected - retry to connect to the AP
I (11637) LockHandler: Requesting favicon
I (11637) ESP32 NAT router: retry to connect to the AP
W (12537) httpd_uri: httpd_uri: URI '/generate_204' not found
W (13687) httpd_uri: httpd_uri: URI '/generate_204' not found
I (14457) wifi:<ba-add>idx:3 (ifx:1, 0c:c6:fd:34:e3:66), tid:7, ssn:2, winSize:64
I (14487) ESP32 NAT router: disconnected - retry to connect to the AP
I (14487) ESP32 NAT router: retry to connect to the AP
I (17327) ESP32 NAT router: disconnected - retry to connect to the AP
I (17327) ESP32 NAT router: retry to connect to the AP
I (20167) ESP32 NAT router: disconnected - retry to connect to the AP
I (20167) ESP32 NAT router: retry to connect to the AP
I (23007) ESP32 NAT router: disconnected - retry to connect to the AP
I (23007) ESP32 NAT router: retry to connect to the AP
I (25847) ESP32 NAT router: disconnected - retry to connect to the AP
I (25847) ESP32 NAT router: retry to connect to the AP
I (28687) ESP32 NAT router: disconnected - retry to connect to the AP
I (28687) ESP32 NAT router: retry to connect to the AP
I (29877) DNSServer: Received 29 bytes from 192.168.4.2 | DNS reply with len: 45
I (29877) DNSServer: Waiting for data
I (31527) ESP32 NAT router: disconnected - retry to connect to the AP
I (31527) ESP32 NAT router: retry to connect to the AP
I (34337) DNSServer: Received 39 bytes from 192.168.4.2 | DNS reply with len: 55
I (34347) DNSServer: Waiting for data
I (34347) DNSServer: Received 46 bytes from 192.168.4.2 | DNS reply with len: 62
I (34357) DNSServer: Waiting for data
I (34367) ESP32 NAT router: disconnected - retry to connect to the AP
I (34367) ESP32 NAT router: retry to connect to the AP
I (37207) ESP32 NAT router: disconnected - retry to connect to the AP
I (37207) ESP32 NAT router: retry to connect to the AP
I (40047) ESP32 NAT router: disconnected - retry to connect to the AP
I (40047) ESP32 NAT router: retry to connect to the AP
I (42887) ESP32 NAT router: disconnected - retry to connect to the AP
I (42887) ESP32 NAT router: retry to connect to the AP
I (43647) DNSServer: Received 39 bytes from 192.168.4.2 | DNS reply with len: 55
I (43647) DNSServer: Waiting for data
I (45727) ESP32 NAT router: disconnected - retry to connect to the AP
I (45737) ESP32 NAT router: retry to connect to the AP
I (48567) ESP32 NAT router: disconnected - retry to connect to the AP
I (48577) ESP32 NAT router: retry to connect to the AP
I (51417) ESP32 NAT router: disconnected - retry to connect to the AP
I (51417) ESP32 NAT router: retry to connect to the AP
I (54247) ESP32 NAT router: disconnected - retry to connect to the AP
I (54257) ESP32 NAT router: retry to connect to the AP
I (57087) ESP32 NAT router: disconnected - retry to connect to the AP
I (57097) ESP32 NAT router: retry to connect to the AP
I (59927) ESP32 NAT router: disconnected - retry to connect to the AP
I (59937) ESP32 NAT router: retry to connect to the AP
I (62767) ESP32 NAT router: disconnected - retry to connect to the AP
I (62777) ESP32 NAT router: retry to connect to the AP
I (65607) ESP32 NAT router: disconnected - retry to connect to the AP
I (65607) ESP32 NAT router: retry to connect to the AP
I (68447) ESP32 NAT router: disconnected - retry to connect to the AP
I (68447) ESP32 NAT router: retry to connect to the AP
I (71287) ESP32 NAT router: disconnected - retry to connect to the AP
I (71287) ESP32 NAT router: retry to connect to the AP

**Comment by dchristl** [comment]
Hello @pcouderc12 ,

it is not so easy to build with the native toolchain, because this project is build with platformio. You have to change the whole layout (folders, includes, setting, ...) to make this work. Have you already seen [my instructions how to build](https://github.com/dchristl/esp32_nat_router_extended/blob/master/docs/BUILD.md)? I will not recommend and support other builds than with platformio. 

Regards,
Danny

**Comment by pcouderc12** [comment]
Sorry that your are wrong. It is very easy to build with native toolchain and I have given the way to do that in #68...
But you are free to not recommand and not support it. And to not try answering my problem.

**Comment by dchristl** [comment]
I know what to do, because I've done it the other way round when I started this project. ;) In my opinion it is not very easy, because you have to do these steps everytime when there is any code change in this project. Otherwise you get a lot of merge conflicts. It is not that I don't want to help you, but I can't and don't recommend it. I don't see your setup, because maybe there is something wrong. Do you have this problems when building with platformio or using my release, too?
Btw. what is the advantage by building with the native toolchain, because platformio uses this under the hood, too. But with a uniformed folder structure (same for every supported microcontroller, independent from vendor's toolchain)

**Comment by pcouderc12** [comment]
All and the only setup I have done is indicated in #68...
And this is certainly the problem, I am missing something.
I do not use platformio... because I have started with native toolchain and did see no interest in other  environnement. And I am sure I may be wrong...
Thanks anyway !

**Comment by dchristl** [comment]
The only thing what you can try is to replace the content of your sdkconfig with mine, dependent on your chip (i.e. sdkconfig.esp32dev for esp32), because I changed more settings than just the ones you mentioned (i.e CONFIG_HTTPD_MAX_REQ_HDR_LEN). 
The second option is to use one of my binaries to exclude issues with your chip or any issues with my code.

**Comment by pcouderc12** [comment]
Thank you, these are 2 interesting ways. My chip couldbe a problem.

**Comment by pcouderc12** [comment]
There is some mystery in  my installation, as I have changed the esp32 device, and even the devkit. And I have tried with esp32nat_extended_full_v5.1.0.bin and even Martin Ger binary. Every time, I success connecting  to http server to program the router, but after  reset, I get AP disconnections.... No more ideas now.

**Comment by dchristl** [comment]
Could you give me an actual log?

**Comment by pcouderc12** [comment]
Sure !
log done under debian using minicom, after erasing flash with :
esptool.py --chip esp32 erase_flash
flashing with:
esptool.py write_flash 0x0  esp32nat_extended_full_v5.1.0.bin
then starting minicom
then connecting debian to ESP32_NAT_Router
then filling parametes with http server (open networls), then restarting with hhtp server :


I (580) cpu_start: Pro cpu up.
I (580) cpu_start: Starting app cpu, entry point is 0x40082188
I (0) cpu_start: App cpu up.
I (594) cpu_start: Pro cpu start user code
I (594) cpu_start: cpu freq: 160000000 Hz
I (594) cpu_start: Application information:
I (599) cpu_start: Project name:     esp32_nat_router
I (605) cpu_start: App version:      134c8ce-dirty
I (610) cpu_start: Compile time:     Jun  2 2023 15:39:03
I (616) cpu_start: ELF file SHA256:  8db8daf4413a8365...
I (622) cpu_start: ESP-IDF:          5.0.2
I (627) cpu_start: Min chip rev:     v0.0
I (632) cpu_start: Max chip rev:     v3.99
I (637) cpu_start: Chip rev:         v3.0
I (642) heap_init: Initializing. RAM available for dynamic allocation:
I (649) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (655) heap_init: At 3FFB7D68 len 00028298 (160 KiB): DRAM
I (661) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (667) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (674) heap_init: At 4009760C len 000089F4 (34 KiB): IRAM
I (681) spi_flash: detected chip: generic
I (685) spi_flash: flash io: dio
I (690) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (724) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (734) ESP32 NAT router: Device will boot up normally.
I (754) ESP32 NAT router: Command history disabled
I (754) ESP32 NAT router: Netmask is set to 255.255.255.0, therefore private IP is 192.168.4.1
I (774) wifi:wifi driver task: 3ffc2500, prio:23, stack:3584, core=0
I (774) system_api: Base MAC address is not set
I (774) system_api: read default base MAC address from EFUSE
I (784) wifi:wifi firmware version: 57982fe
I (784) wifi:wifi certification version: v7.0
I (794) wifi:config NVS flash: enabled
I (794) wifi:config nano formating: disabled
I (804) wifi:Init data frame dynamic rx buffer num: 32
I (804) wifi:Init management frame dynamic rx buffer num: 32
I (804) wifi:Init management short buffer num: 32
I (814) wifi:Init dynamic tx buffer num: 32
I (814) wifi:Init static rx buffer size: 1600
I (814) wifi:Init static rx buffer num: 10
I (824) wifi:Init dynamic rx buffer num: 32
I (834) wifi_init: rx ba win: 6
I (834) wifi_init: tcpip mbox: 32
I (834) wifi_init: udp mbox: 6
I (844) wifi_init: tcp mbox: 6
I (844) wifi_init: tcp tx win: 5744
I (844) wifi_init: tcp rx win: 5744
I (854) wifi_init: tcp mss: 1440
I (854) wifi_init: WiFi IRAM OP enabled
I (854) wifi_init: WiFi RX IRAM OP enabled
I (884) ESP32 NAT router: set dns to: 192.168.4.1
I (2884) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
W (2884) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration
I (3044) wifi:mode : softAP (cc:db:a7:1e:3f:29)
I (3044) wifi:Total power save buffer number: 16
I (3044) wifi:Init max length of beacon: 752/752
I (3054) wifi:Init max length of beacon: 752/752
I (3064) ESP32 NAT router: wifi_init_ap with default finished.
I (3064) DNSServer: DNS Server started
I (3064) DNSServer: Socket created
I (3064) DNSServer: Socket bound, port 53
I (3084) DNSServer: Waiting for data
I (3074) ESP32 NAT router: On board LED is enabled
I (3084) gpio: GPIO[2]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (3084) ESP32 NAT router: NAT is enabled
I (3094) ESP32 NAT router: Starting config web server
I (3104) HTTPServer: Keep alive is disabled
I (3114) HTTPServer: Starting server on port: '80'
I (3124) HTTPServer: Registering URI handlers


ESP32 NAT ROUTER
Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.

Unconfigured WiFi
Configure using 'set_sta' and 'set_ap' and restart.
esp32> I (45334) wifi:new:<1,1>, old:<1,1>, ap:<1,1>, sta:<255,255>, prof:1
I (45334) wifi:station: 90:e8:68:41:d5:89 join, AID=1, bgn, 40U
I (45334) ESP32 NAT router: Station connected
I (45434) wifi:<ba-add>idx:2 (ifx:1, 90:e8:68:41:d5:89), tid:0, ssn:1, winSize:64
I (49554) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.4.2
I (50254) DNSServer: Received 34 bytes from 192.168.4.2 | DNS reply with len: 50
I (50254) DNSServer: Waiting for data
I (50264) DNSServer: Received 34 bytes from 192.168.4.2 | DNS reply with len: 50
I (50274) DNSServer: Waiting for data
I (51544) DNSServer: Received 38 bytes from 192.168.4.2 | DNS reply with len: 54
I (51544) DNSServer: Waiting for data
I (51554) DNSServer: Received 38 bytes from 192.168.4.2 | DNS reply with len: 54
I (51564) DNSServer: Waiting for data
I (64144) IndexHandler: Allocating additional 7283 bytes for config page.
I (64244) LockHandler: Requesting favicon
I (75544) DNSServer: Received 33 bytes from 192.168.4.2 | DNS reply with len: 49
I (75554) DNSServer: Waiting for data
I (75554) DNSServer: Received 33 bytes from 192.168.4.2 | DNS reply with len: 49
I (75564) DNSServer: Waiting for data
I (75564) DNSServer: Received 33 bytes from 192.168.4.2 | DNS reply with len: 49
I (75574) DNSServer: Waiting for data
I (75574) DNSServer: Received 33 bytes from 192.168.4.2 | DNS reply with len: 49
I (75584) DNSServer: Waiting for data
I (100304) ApplyHandler: Content length  => 112
I (100304) ApplyHandler: 113 bytes total received -> 0 left
I (100304) ApplyHandler: getting content func=config&ap_ssid=ESP32_NAT_Router&ap_password=+&ssid=TP-LINK_2872&sta_identity=&sta_user=&cer=&password=+&x=x¥
I (100324) urihelper: Found 'func' parameter => config
I (100334) ApplyHandler: Function => config
I (100334) urihelper: Found 'ap_ssid' parameter => ESP32_NAT_Router
I (100344) urihelper: Found 'ap_password' parameter =>
I (100354) urihelper: Found 'ssid' parameter => TP-LINK_2872
I (100354) urihelper: Found 'password' parameter =>
I (100354) urihelper: Found 'sta_identity' parameter =>
I (100374) ApplyHandler: WPA2 Identity will be deleted
I (100374) urihelper: Found 'sta_user' parameter =>
I (100374) ApplyHandler: WPA2 user will be deleted
I (100394) urihelper: Found 'cer' parameter =>
I (100394) ApplyHandler: Certificate will be deleted
I (100394) ApplyHandler: Requesting apply page
I (100394) ApplyHandler: Host of request is '192.168.4.1'
I (100414) ApplyHandler: Redirecting after apply to 'http://192.168.4.1'
I (100464) LockHandler: Requesting favicon
I (100894) Timer: Restarting now...
I (100904) wifi:station: 90:e8:68:41:d5:89 leave, AID = 1, bss_flags is 134243, bss:0x3ffdd3dc
I (100904) wifi:new:<1,0>, old:<1,1>, ap:<1,1>, sta:<255,255>, prof:1
I (100914) wifi:<ba-del>idx
I (100904) ESP32 NAT router: Station disconnected
I (100974) wifi:flush txq
I (100974) wifi:stop sw txq
I (100974) wifi:lmac stop hw txq
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:5744
load:0x40078000,len:15048
load:0x40080400,len:3484
entry 0x400805ec
I (516) cpu_start: Pro cpu up.
I (516) cpu_start: Starting app cpu, entry point is 0x40082188
I (503) cpu_start: App cpu up.
I (530) cpu_start: Pro cpu start user code
I (530) cpu_start: cpu freq: 160000000 Hz
I (530) cpu_start: Application information:
I (535) cpu_start: Project name:     esp32_nat_router
I (541) cpu_start: App version:      134c8ce-dirty
I (546) cpu_start: Compile time:     Jun  2 2023 15:39:03
I (552) cpu_start: ELF file SHA256:  8db8daf4413a8365...
I (558) cpu_start: ESP-IDF:          5.0.2
I (563) cpu_start: Min chip rev:     v0.0
I (568) cpu_start: Max chip rev:     v3.99
I (573) cpu_start: Chip rev:         v3.0
I (578) heap_init: Initializing. RAM available for dynamic allocation:
I (585) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (591) heap_init: At 3FFB7D68 len 00028298 (160 KiB): DRAM
I (597) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (603) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (610) heap_init: At 4009760C len 000089F4 (34 KiB): IRAM
I (618) spi_flash: detected chip: generic
I (621) spi_flash: flash io: dio
I (626) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (698) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (698) ESP32 NAT router: Device will boot up normally.
I (718) ESP32 NAT router: Command history disabled
I (728) cmd_router: ssid TP-LINK_2872
I (728) cmd_router: passwd
I (738) cmd_router: ap_ssid ESP32_NAT_Router
I (738) ESP32 NAT router: Netmask is set to 255.255.255.0, therefore private IP is 192.168.4.1
I (758) wifi:wifi driver task: 3ffc2754, prio:23, stack:3584, core=0
I (758) system_api: Base MAC address is not set
I (758) system_api: read default base MAC address from EFUSE
I (778) wifi:wifi firmware version: 57982fe
I (778) wifi:wifi certification version: v7.0
I (778) wifi:config NVS flash: enabled
I (778) wifi:config nano formating: disabled
I (788) wifi:Init data frame dynamic rx buffer num: 32
I (788) wifi:Init management frame dynamic rx buffer num: 32
I (788) wifi:Init management short buffer num: 32
I (808) wifi:Init dynamic tx buffer num: 32
I (808) wifi:Init static rx buffer size: 1600
I (808) wifi:Init static rx buffer num: 10
I (818) wifi:Init dynamic rx buffer num: 32
I (818) wifi_init: rx ba win: 6
I (818) wifi_init: tcpip mbox: 32
I (818) wifi_init: udp mbox: 6
I (828) wifi_init: tcp mbox: 6
I (828) wifi_init: tcp tx win: 5744
I (828) wifi_init: tcp rx win: 5744
I (848) wifi_init: tcp mss: 1440
I (848) wifi_init: WiFi IRAM OP enabled
I (848) wifi_init: WiFi RX IRAM OP enabled
I (898) ESP32 NAT router: set dns to: 192.168.4.1
I (2898) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (2998) wifi:mode : sta (cc:db:a7:1e:3f:28) + softAP (cc:db:a7:1e:3f:29)
I (2998) wifi:enable tsf
I (2998) wifi:Total power save buffer number: 16
I (2998) wifi:Init max length of beacon: 752/752
I (3008) wifi:Init max length of beacon: 752/752
I (3018) ESP32 NAT router: wifi_init_apsta finished.
I (3018) ESP32 NAT router: connect to ap SSID: TP-LINK_2872 Password:
I (3018) DNSServer: DNS Server started
I (3018) DNSServer: Socket created
I (3028) DNSServer: Socket bound, port 53
I (3038) DNSServer: Waiting for data
I (3038) ESP32 NAT router: On board LED is enabled
I (3048) gpio: GPIO[2]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (3048) ESP32 NAT router: NAT is enabled
I (3058) ESP32 NAT router: Starting config web server
I (3058) HTTPServer: Keep alive is disabled
I (3068) HTTPServer: Starting server on port: '80'
I (3078) HTTPServer: Registering URI handlers


ESP32 NAT ROUTER
Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.
esp32> I (5858) ESP32 NAT router: disconnected - retry to connect to the AP
I (5858) ESP32 NAT router: retry to connect to the AP
I (8698) ESP32 NAT router: disconnected - retry to connect to the AP
I (8698) ESP32 NAT router: retry to connect to the AP
I (11538) ESP32 NAT router: disconnected - retry to connect to the AP
I (11548) ESP32 NAT router: retry to connect to the AP
I (14378) ESP32 NAT router: disconnected - retry to connect to the AP
I (14388) ESP32 NAT router: retry to connect to the AP
I (17228) ESP32 NAT router: disconnected - retry to connect to the AP
I (17228) ESP32 NAT router: retry to connect to the AP
I (20068) ESP32 NAT router: disconnected - retry to connect to the AP
I (20068) ESP32 NAT router: retry to connect to the AP
I (22908) ESP32 NAT router: disconnected - retry to connect to the AP
I (22908) ESP32 NAT router: retry to connect to the AP
I (25748) ESP32 NAT router: disconnected - retry to connect to the AP
I (25758) ESP32 NAT router: retry to connect to the AP
I (28588) ESP32 NAT router: disconnected - retry to connect to the AP
I (28598) ESP32 NAT router: retry to connect to the AP
I (31438) ESP32 NAT router: disconnected - retry to connect to the AP
I (31438) ESP32 NAT router: retry to connect to the AP
I (34278) ESP32 NAT router: disconnected - retry to connect to the AP
I (34278) ESP32 NAT router: retry to connect to the AP
I (37118) ESP32 NAT router: disconnected - retry to connect to the AP
I (37118) ESP32 NAT router: retry to connect to the AP
I (39958) ESP32 NAT router: disconnected - retry to connect to the AP
I (39968) ESP32 NAT router: retry to connect to the AP
I (42798) ESP32 NAT router: disconnected - retry to connect to the AP
I (42808) ESP32 NAT router: retry to connect to the AP
I (45648) ESP32 NAT router: disconnected - retry to connect to the AP
I (45648) ESP32 NAT router: retry to connect to the AP
I (48488) ESP32 NAT router: disconnected - retry to connect to the AP
I (48488) ESP32 NAT router: retry to connect to the AP
I (51328) ESP32 NAT router: disconnected - retry to connect to the AP
I (51328) ESP32 NAT router: retry to connect to the AP
I (54168) ESP32 NAT router: disconnected - retry to connect to the AP
I (54178) ESP32 NAT router: retry to connect to the AP
I (57018) ESP32 NAT router: disconnected - retry to connect to the AP
I (57018) ESP32 NAT router: retry to connect to the AP
.....

**Comment by dchristl** [comment]
Sadly, I don't see something suspicious in your log. Do you have the chance to use an other ESP32 or to connect to another router (i.e. mobile hotspot) with and without encryption?

**Comment by pcouderc12** [comment]
Thank you again. I had soon tried to change device. But using an Androïd hotspot, your provided esp32nat_extended_full_v5.1.0.bin works perfectly...  Maybe it is the strenght of the STA signal, even if I do not see why problem with the STA implies a problem with with  AP...

**Comment by dchristl** [comment]
The funny part is, that this is just an mistake in the log, that I have already carried over from the original project  ;) This isn't the AP, but the STA. So, this 
> ESP32 NAT router: disconnected - retry to connect to the AP
 ESP32 NAT router: retry to connect to the AP

have to be:
> ESP32 NAT router: disconnected - retry to connect to the STA
 ESP32 NAT router: retry to connect to the STA

Therefore, it is quite possible that it is due to the distance or poor connection. When you scan, is the access point included?

**Comment by pcouderc12** [comment]
Mmm, well when scanning, I see and I test with distance from Android augmenting more or less,and so stregnth of signal varying. I have good results with strgnth of signl very low (lower than with the  TP-LINK_2872  open router).
Anyway, I do not understand  why when there is this "ESP32 NAT router: disconnected - retry to connect to the STA" message, I cannot access to 192.168.4.1 page...

**Comment by pcouderc12** [comment]
In fact, I do not see in esp32_nat_router.c where wifi_config.sta.authmode is set to  WIFI_AUTH_OPEN when passwd is less than 8  chars. I could explain my problem with my  STA which is open !

**Comment by pcouderc12** [comment]
After changing the open router from  WIFI_AUTH_OPEN  to default with password, works perfectly.

**Comment by dchristl** [comment]
Great to hear that it works perfectly now. 

> In fact, I do not see in esp32_nat_router.c where wifi_config.sta.authmode is set to WIFI_AUTH_OPEN when passwd is less than 8 chars. It could explain my problem with my STA which is open !

This is normally not needed, because the router and the ESP32 will figure this out for themselves. Maybe something has changed in the framework or it doesn't work with all routers.

> After changing the open router from WIFI_AUTH_OPEN to default with password, works perfectly.

What is the current state now, because you have opened another issue (#70 ) Does it work without these code changes  or onyl when you compile it for yourself? If you need the code changes I will have a deeper look into this. 

Thank you

**Comment by pcouderc12** [comment]
Thank you, I did open it, before I had the idea to reprogram the TP_LINK router. And as, after reprogramming this router, the problem is not reproducible, so no need to look for a ghost, and I did close it. Thank you very much for your help. I prepare a version of the routing engine without any dialog, roughly only wifi(...)  and no http or console. For me  and for anyone if it helps...
