### ISSUE TITLE
No Wifi after uploading

### ISSUE THREAD

**Issue by richardwpaul** [dchristl/esp32_nat_router_extended#76]
A new ESP32. I followed your directions for uploading using windows graphic interface. Everything went as you describe in your directions with no errors. I rebooted the esp32. However there is no WiFi output from esp32.  Your suggestions, please.

**Comment by dchristl** [comment]
Hello @richardwpaul ,

my first guess is, that you have either used the wrong version (full/upgrade) or the wrong address. You have to use the **full** version on address **0x0** on new devices. Have  you checked that and all the setings provided in the scressnshot? 
Otherwise please share a screenshot of your settings with the log (the cli window) included.

Regards,
Danny

**Comment by richardwpaul** [comment]
Here are my steps: Load full, unplug to rebootNo wifiChange address and load update, unplug to rebootNo wifiLast image is from serial port when I reboot. Rick Paul765.430.5389*HP*gmail From: dchristlSent: Wednesday, August 9, 2023 1:04 AMTo: dchristl/esp32_nat_router_extendedCc: richardwpaul; MentionSubject: Re: [dchristl/esp32_nat_router_extended] No Wifi after uploading (Issue #76) Hello @richardwpaul ,my first guess is, that you have either used the wrong version (full/upgrade) or the wrong address. You have to use the full version on address 0x0 on new devices. Have you checked that and all the setings provided in the scressnshot?Otherwise please share a screenshot of your settings with the log (the cli window) included.Regards,Danny—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by richardwpaul** [comment]
Danny, Here is what I did. Erased flash, uploaded, rebooted. Still no WIFI Rick Paul765.430.5389*HP*gmail From: dchristlSent: Wednesday, August 9, 2023 1:04 AMTo: dchristl/esp32_nat_router_extendedCc: richardwpaul; MentionSubject: Re: [dchristl/esp32_nat_router_extended] No Wifi after uploading (Issue #76) Hello @richardwpaul ,my first guess is, that you have either used the wrong version (full/upgrade) or the wrong address. You have to use the full version on address 0x0 on new devices. Have you checked that and all the setings provided in the scressnshot?Otherwise please share a screenshot of your settings with the log (the cli window) included.Regards,Danny—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by richardwpaul** [comment]
Danny, First erased flash. Rick Paul765.430.5389*HP*gmail From: dchristlSent: Wednesday, August 9, 2023 1:04 AMTo: dchristl/esp32_nat_router_extendedCc: richardwpaul; MentionSubject: Re: [dchristl/esp32_nat_router_extended] No Wifi after uploading (Issue #76) Hello @richardwpaul ,my first guess is, that you have either used the wrong version (full/upgrade) or the wrong address. You have to use the full version on address 0x0 on new devices. Have you checked that and all the setings provided in the scressnshot?Otherwise please share a screenshot of your settings with the log (the cli window) included.Regards,Danny—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by richardwpaul** [comment]
Sorry for the email mess. 
![one](https://github.com/dchristl/esp32_nat_router_extended/assets/10798404/3e6538fc-b845-4a0e-acb1-c2b26b003989)
![two](https://github.com/dchristl/esp32_nat_router_extended/assets/10798404/d7a1f93b-8d9b-47fe-87cb-b8756227abc8)

**Comment by dchristl** [comment]
Have you changed the default baud rate? It says 576000 and not 115200. It is not visible in your screenshot (under COM). Please change it and flash again. Some tools are "special" when the folder contains spaces. So please put the download tool and the bin in an folder without it. 
If this will not work either, try to [establish a serial connection](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/establish-serial-connection.html#windows-and-linux) with putty and post the log.

**Comment by richardwpaul** [comment]
Sorry for the email mess.

**Comment by richardwpaul** [comment]
1. erased using esp_tool erase_flash. 2. moved Bin file to Bin directory under flash_download_tool directory. 3. Flashed FULL using 0x0 and 576000. no errors. Image of serial port when booting. Sorry for the hassle.
![three](https://github.com/dchristl/esp32_nat_router_extended/assets/10798404/bdb29af0-c0b3-470a-a1e9-f360c5678dfb)

**Comment by dchristl** [comment]
> 2. moved Bin file to Bin directory under flash_download_tool directory

Your flash download tool directory seems to have a space, too: C:\Users\Rick Paul" ?

> 3. Flashed FULL using 0x0 and 576000. 

Please use **115200** like I mentioned. The wrong baud rate can cause invalid flashing results.

> Invalid header 

Invalid means corrupt image, mostly non exxistent bootloader. Can you try to download the image again?
