### ISSUE TITLE
how to compile for exp32-s3 board?

### ISSUE THREAD

**Issue by epowsal** [dchristl/esp32_nat_router_extended#87]
how to compile for exp32-s3 board?

**Comment by dchristl** [comment]
Have you tried to switch the chip in the dock:
![image](https://github.com/dchristl/esp32_nat_router_extended/assets/2836933/cd8bea2a-f88f-4ed4-82d9-438108242f42)

Here you can switch between the 3 chips

**Comment by epowsal** [comment]
![2023-09-22_222814](https://github.com/dchristl/esp32_nat_router_extended/assets/89308109/28d2c855-1beb-4fa9-b7cd-3157c06c070e)
it didn't have esp32-s3 option.

**Comment by dchristl** [comment]
Sorry, I've misread the S3 for C3. This chip is not supported by this project.
