### ISSUE TITLE
Feature request - Channels

### ISSUE THREAD

**Issue by StruckGuide8154** [dchristl/esp32_nat_router_extended#93]
Is there any possibility you could add picking what channel your network will be on e.g channel 4, currently the repeated network is always on channel one.

**Comment by dchristl** [comment]
Hello @StruckGuide8154,

sadly this is not possible and a technical limitiation of thee ESP32. In softAP-mode (which is needed to get this to work) the STA-channel is always the same as the AP-chanelle and cannot be changed. If you want to use channel 4 for your STA, you have to configure your AP to use channel 4. 

Regards,
Danny
