### ISSUE TITLE
Repeater function

### ISSUE THREAD

**Issue by mkfrcp** [dchristl/esp32_nat_router_extended#97]
Hello,
Very nice UI!

Can you show me how to use your esp32_nat_router as a repeater instead of an extender?
I just want to extend the range of my wifi without changing wifi settings of the clients.

Thank you so much!

**Comment by dchristl** [comment]
Hello @mkfrcp ,
the repeater function is not like a real repeater or router, as this mode is not supported by the ESP32. However, you can simulate this by assigning the same credentials to the ESP32 network as those for the uplink network. The devices will then connect to the strongest signal.

Kind regards,
Danny

**Comment by mkfrcp** [comment]
Hello.

Thanks a lot for your help !

Regards,
